name: Build DEB Package

on:
  push:
    branches: [ "main", "master" ] # 同时兼容 main 和 master
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Tools
        run: sudo apt-get update && sudo apt-get install -p binutils -y

      - name: Prepare and Build
        run: |
          # 创建打包目录
          mkdir -p build/DEBIAN
          mkdir -p build/usr/local/bin
          
          # 检查文件是否存在并解压
          if [ -f "WifiTrigger.zip" ]; then
            unzip WifiTrigger.zip -d build/usr/local/bin/
          else
            echo "错误：找不到 WifiTrigger.zip 文件！"
            ls -R
            exit 1
          fi
          
          # 生成控制文件
          cat <<EOF > build/DEBIAN/control
          Package: wifitrigger
          Version: 1.0.0
          Section: utils
          Priority: optional
          Architecture: amd64
          Maintainer: senyunice
          Description: WifiTrigger plugin
          EOF
          
          # 给予权限并打包
          chmod -R 755 build/
          dpkg-deb --build build wifitrigger.deb

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: my-deb-file
          path: wifitrigger.deb
